server:
  port: 8091
  error:
    include-message: always

eureka:
  instance:
    instance-id: ${spring.application.name}:@project.version@
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

application:
  http-client:
    security-authentication:
      base-url: http://localhost:8085
      exclude-paths:
        -
          method: POST
          path: /srv/neg/v1/security-authentication/generate
        -
          method: POST
          path: /srv/neg/v1/security-authentication/validate
        -
          method: POST
          path: /srv/neg/v1/security-authentication/users

spring:
  application:
    name: 'cloud-api-gateway'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        -
          id: srv-neg-employee-configuration-v1
          uri: http://localhost:8081
          predicates:
            - Path=/srv/neg/v1/employee-configuration/**
        -
          id: srv-neg-security-authentication-v1
          uri: http://localhost:8085
          predicates:
            - Path=/srv/neg/v1/security-authentication/**
        -
          id: srv-neg-audit-configuration-v1
          uri: http://localhost:8081
          predicates:
            - Path=/srv/neg/v1/audit-configuration/**

logging:
  level:
    com.pe.relari: TRACE